pipeline {
  agent any
  stages {
    stage ("Prompt for input") {
      steps {
        script {
          env.QUERY = input message: 'Please enter your query',
                             parameters: [string(defaultValue: '',
                                          description: '',
                                          name: 'Query')]
          env.Collection = input message: 'Please enter your collection',
                         parameters: [string(defaultValue: '',
                                      description: '',
                                      name: 'Collection')]
        }
        echo "Youre Query: ${env.Query}"
        echo "Youre Collection: ${env.Collection}"
        echo "mongoexport --db=okiano-prod --collection='${env.Collection}' --query='${env.Query}' --out=${env.Collection}.json"
      }
    }
  }
}
